/*
 * Assembles the standalone player from web/ + the cart.
 *
 *   node web/build.mjs
 *
 * Produces two files from one source, because the two targets need different
 * wrappers:
 *   dist/orbit.html           full HTML document - open it in a browser
 *   dist/orbit.artifact.html  body-only fragment - for publishing as an Artifact
 *
 * Uses node builtins only: no install, no lockfile.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');

const cart = read('orbit.p8');
const shell = read('web/shell.html');

// Literal replacement: a plain string would let `$&` in the payload expand.
function fill(haystack, token, payload) {
  if (!haystack.includes(token)) throw new Error(`placeholder ${token} missing from shell.html`);
  return haystack.replace(token, () => payload);
}

let out = shell;
out = fill(out, '/*{{ENGINE_JS}}*/', read('web/engine.js'));
out = fill(out, '/*{{RUNTIME_JS}}*/', read('web/runtime.js'));
out = fill(out, '/*{{HOST_JS}}*/', read('web/host.js'));
// Escaping `<` keeps a cart containing "</script>" from closing the tag early.
// \u003c is still a plain `<` to the JS parser, so the Lua source is unchanged.
// The token swallows the `""` fallback too - leaving it would emit two
// adjacent string literals, which is a syntax error.
out = fill(out, '/*{{CART_JSON}}*/ ""', JSON.stringify(cart).replace(/</g, '\\u003c'));

const banner = '<!-- Generated by web/build.mjs - edit web/shell.html or the cart, not this file. -->\n';

// Compile every inline script. `new Function` parses without executing, so a
// syntax error in the generated page fails the build instead of the browser.
const inline = [...out.matchAll(/<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/g)];
if (inline.length === 0) throw new Error('no inline scripts found - shell.html changed shape?');
inline.forEach(([, code], i) => {
  try {
    new Function(code);
  } catch (err) {
    throw new Error(`inline script #${i + 1} has a syntax error: ${err.message}`);
  }
});
console.log(`syntax-checked ${inline.length} inline scripts`);

const dist = path.join(root, 'dist');
fs.mkdirSync(dist, { recursive: true });

const doc = [
  '<!doctype html>',
  '<html lang="en">',
  '<meta charset="utf-8">',
  '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">',
  banner.trim(),
  out,
  '</html>',
  ''
].join('\n');

fs.writeFileSync(path.join(dist, 'orbit.html'), doc);
fs.writeFileSync(path.join(dist, 'orbit.artifact.html'), banner + out);

const kb = (s) => (Buffer.byteLength(s) / 1024).toFixed(1) + ' KB';
console.log('dist/orbit.html          ' + kb(doc));
console.log('dist/orbit.artifact.html ' + kb(banner + out));
